# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: OnlyFacts🇺🇸
email: robert.jamison2@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  If you're looking for a reliable US-based source on "just the facts",
  look no further. From cybersecurity to data science, you'll find exactly
  what you need here at OnlyFacts.
twitter_username: username
github_username: robertjamison
minimal_mistakes_skin: dark
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: America/New_York # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Robert Jamison"
  avatar : "/assets/images/rjamison.jpeg"
  bio    : >- # this means to ignore newlines until "baseurl:"
    With over 14 years of Signal and Cyber experience in the 
    Army National Guard, Robert is currently one of the lead 
    writers for Strategic I.T. Policy at the National Guard Bureau.
  location: "Arlington, Virginia"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-at"
      url: "robert.jamison2@gmail.com"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/robertgjamison"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/robertjamison"

footer:
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/robertgjamison"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/robertjamison"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
